version: '2'
services:
  nginx:
    image: matter/shibboleth-nginx
    container_name: nginx
    restart: always
    environment:
      - CLIENT_APP_HOSTNAME=devops.lxnode.net
      - NGINX_PROXY_DESTINATION=http://127.0.0.1:8001
    volumes:
      - ./log:/var/log
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/wordpress:/var/www/html:ro

    depends_on:
#      - mysql
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      - front
  php:
    image: evild/alpine-wordpress:latest
    container_name: php
    restart: always
    volumes:
      - ./data//wordpress:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
#    depends_on:
#      - mysql
    environment:
      - WORDPRESS_DEBUG=true
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=34.196.80.124
      - WORDPRESS_DB_PASSWORD=root
    networks:
      - front
      - back
#  mysql:
#    image: mariadb:10
#    container_name: mysql
#    restart: always
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#    networks:
#      - back
networks:
  front:
  back:
